#!/bin/bash

function color (){
  echo "\e[$1m$2\e[0m"
}

function setCountColor (){
  local input=$1
  countColor="38;5;16;48;5;242"

  if [ $input == 0 ]; then
    countColor="38;5;16;48;5;242"
  else
    countColor="38;5;16;48;5;71"
  fi
}

function msgFormat (){
  local input=$1
  local packagesPlural="s"

  if [[ $input -eq 0 ||  $input -eq 1 ]]; then
    packagesPlural=""
  fi
  echo "package$packagesPlural"
}

msgColor="38;5;103"
statsLabelColor="38;5;143"
bulletColor="38;5;241"
infoColor="38;5;74"
dimInfoColor="38;5;7;2"

# Count
apt-get update --quiet=2
pkgCount="$(apt-get -s dist-upgrade | grep -Po '^\d+(?= upgraded)')"
setCountColor "$pkgCount"

# Check Unbound
# Get the latest release tag from the Unbound GitHub repository
msgUnboundUpdate=""
latest_release=$(curl -s https://api.github.com/repos/NLnetLabs/unbound/tags | grep -oP '"name": "\K([^"]+)' | grep -v "alpha" | head -1 | sed 's/^release-//')
current_version=$(unbound -V | grep Version | awk '{print $2}')
if [[ $current_version < $latest_release ]]; then
  msgUnboundUpdate="$(color $statsLabelColor "|") $(color $msgColor "Unbound available:") $(color $infoColor $current_version) $(color $statsLabelColor "»") $(color $infoColor $latest_release)"
fi

# Message
msgHeader="$(color $msgColor ▶)"
msgCount="$(color $countColor " $pkgCount ")"
msgLabel="$(color $msgColor "$(msgFormat $pkgCount) can be upgraded")"

updateMsg=" $msgHeader $msgCount $msgLabel $msgUnboundUpdate"

# Output To Static Script
OUT="/etc/update-motd.d/"$(basename $0)
exec >${OUT}
echo "#!/bin/bash"
echo
echo "#####################################################"
echo "#              DO NOT EDIT THIS SCRIPT              #"
echo "#     EDIT: /etc/update-motd-static.d/20-update     #"
echo "#####################################################"
echo "cat <<EOF"
echo -e "\n$updateMsg\n"
echo "EOF"
